### 일반유저가 이사요청을 생성
POST http://localhost:4000/api/move-requests
Content-Type: application/json

{
  "serviceType": "SMALL",
  "moveDate": "2025-12-25",
  "departure": "경기도 남양주시 화도읍",
  "departureRegion": "경기",
  "destination": "제주 서귀포시 동홍동",
  "destinationRegion": "제주"
}


###
POST http://localhost:4000/api/auth/mover/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678",
  "phone": "01012345678",
  "nickname": "test",
  "career": "1년",
  "introduction": "편안한 이사를 돕겠습니다",
  "description": "물건 훼손이나 분실 걱정 없게 확실하게 도와드립니다 단 한 번도 사고난 적 없습니다"
}

###
POST http://localhost:4000/api/auth/mover/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

### Mover가 조건에 맞는 이사요청 list 불러오기
POST http://localhost:4000/api/move-requests/search
Content-Type: application/json

{
  "regions": ["경기","서울"]
  # "serviceTypes": ["SMALL"]
}

###
POST http://localhost:4000/api/move-requests/3/quotes
Content-Type: application/json

{
  "moverId": 3,
  "price": 150000,
  "comment": "안전하고 빠른 이사 보장",
  "type": "NORMAL"
}