### 일반유저가 이사요청을 생성
POST http://localhost:4000/api/move-requests
Content-Type: application/json

{
  "serviceType": "FAMILY",
  "moveDate": "2025-12-25",
  "departure": "서울 성북구 장위동",
  "departureRegion": "서울",
  "destination": "제주도 서귀포시 토평동",
  "destinationRegion": "제주"
}


###
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678",
  "phone": "01012345678",
  "nickname": "test",
  "career": "1년",
  "introduction": "편안한 이사를 돕겠습니다",
  "description": "물건 훼손이나 분실 걱정 없게 확실하게 도와드립니다 단 한 번도 사고난 적 없습니다"
}

###
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}